config/routes.rb
Rails.application.routes.draw do



  # Devise Related Routes
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations' }

  # You can have the root of your site routed with "root"


  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
      resources :users do
        resources :emails
      end
    end

    #post 'create_email/:user_id/emails', to: 'emails#create', as: :create_user_email
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserMailerRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id="header" class="navbar navbar-fixed-top">
  <div id="header-container" class="container navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="brand" class="navbar-brand" href="#">Mailing System</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% unless current_user.nil? %>
        <td><%= link_to 'Users', users_path %></td>
        <td><%= link_to 'Outbox', user_emails_path(current_user.id) %></td>
        <td><%= link_to 'Logout', destroy_user_session_path, method: 'delete'  %></td>
        <% end %>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav>

<div class="container" >
<%= yield %>
</div>
</body>
</html>